### PR TITLE
Adding template examples

### PR DESCRIPTION
**Pull request by DeeJayTC**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                                |
| New feature?    | yes                               |
| New sample?     | yes                               |

## What's in this Pull Request?

Added template and data examples for the current samples, samples where it made sense now have a ".template.json" and ".data.json"

Created templates for
* Calendar Card
* Event Schedule (despite being fake in parts)
* Praise Card
* Inventory Card

More later :)

### CODE REVIEW

**Comment by DeeJayTC** [comment]
@VesaJuvonen Can you have a look please? :)

**Comment by VesaJuvonen** [comment]
Awesome - these are looking really clean and useful. Highly helpful on explaining also the difference between the template and data. Thanks @DeeJayTC for these 👏

**Comment by VesaJuvonen** [comment]
and sorry for the small delay here - awesome stuff - thanks for helping others to understand the power of Adaptive Cards with these

**Comment by DeeJayTC** [comment]
Welcome! Will add a few more aswell.

**Comment by VesaJuvonen** [comment]
I'll also update the readme file for the samples to have your name and the update date... really great stuff on this 🚀

**Pull request merged**
